### ISSUE TITLE
Implement Data Loading

### ISSUE THREAD

**Issue by Akettle44** [Akettle44/SRGAN-PyTorch#1]
Goal: Load image data into PyTorch efficiently. 

How: Factory design pattern + abstract data loading class

Design Inspiration: https://github.com/Akettle44/LLMs-What-Can-Pruning-Tell-Us/tree/main/src/data
Suggested change: Instead of encoding, perform the gaussian kernel + downsampling on the image.

Concrete Classes (for now): Need the ability to load in CIFAR-10 and apply the gaussian kernel + downsampling operation from section 2 of the paper. 

Acceptance Criteria: Created abstract class for loading data with relevant metadata. Implemented concrete class pertaining to Cifar-10. Implemented factory to handle object instantiation. Unit tests verifying that loading data using Cifar-10 works properly.

**Comment by FeilongHou** [comment]
VOC2012 for higher-resolution images.
